name: appjeshua
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^3.1.3
  flutter_icons: ^1.1.0
  tuple: ^1.0.3
  intl: ^0.15.8
  transparent_image: ^1.0.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  carousel_slider: ^2.2.1
  lottie: ^0.5.1
  shared_preferences: ^0.5.12+4
  webview_flutter: ^1.0.6 
  badges: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/  
